[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

# [profile.dev]
# debug = 0

[workspace.package]
version = "1.0.0"
authors = ["Pagoda <hello@near.org>"]
edition = "2021"

[workspace]
members = ["contracts/*", "op-stack/optimism-rs"]

[workspace.dependencies]

# Nostd
near-sdk = "4.0.0"

# Std aware
